### ISSUE TITLE
Remove decode() in io.py for yoda.__version__

### ISSUE THREAD

**Issue by jackal1-66** [HEPonHPC/apprentice#12]
**Describe the bug**
yoda.__version__ does not need decode in io.py

**To Reproduce**
1. Installed YODA 1.9.8
2. Installed Apprentice 
3. Run yoda-datadirtojson

**Expected behavior**
The version comparison should work

**Desktop (please complete the following information):**
 - OS: CentOS7 
 - Version 7.9.2009

**Additional context**
I tested only one version of YODA(1.9.8) however I don't see any commits on the __version__ format in the official YODA gitlab repository. I must add that I used Python 3.10.13 in case it helps

**Comment by smrenna** [comment]
Making your change caused a problem on my side, so the effect must be
in our versions of code.

**Comment by smrenna** [comment]
The command is "app-datadirtojson".  I have changed the check on versioning in the master, so I am going to resolve this.
